server:
  port: 8081
  servlet:
    context-path: /api/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update

---

server:
  port: 8081
  servlet:
    context-path: /api/

spring:
  config:
    activate:
      on-profile:
      - docker
  datasource:
    url: jdbc:postgresql://postgres:5432/warehouse
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update      